#!/bin/sh

help2man -n "create a list of checksum encoded in hexadecimal format and print to standard output" \
         -N ../bin/jigdo-gen-checksum-list \
	 > jigdo-gen-checksum-list.1

cat jigdo-gen-checksum-list.inc >> jigdo-gen-checksum-list.1 
